### ISSUE TITLE
How do I force redirect :3000 requests?

### ISSUE THREAD

**Issue by bluefangs** [Tarang/Meteor-SSL-proxy#5]
I'm currently using this method to get SSL working. Right now, https://localhost or https://x.x.x.x/ seems to work fine. 
However, I'm still able to access the meteor app via http (localhost:3000 or x.x.x.x:3000). How do I disallow that?

Here is the main.js:

```
var PATH_TO_KEY = "/etc/nginx/ssl/server.key",
    PATH_TO_CERT = "/etc/nginx/ssl/server.crt";
    PATH_TO_CHAIN = "";

var fs = require('fs'),
    httpProxy = require('http-proxy');

var options = {
  ssl: {
    key: fs.readFileSync(PATH_TO_KEY, 'utf8'),
    cert: fs.readFileSync(PATH_TO_CERT, 'utf8'),
    //ca : fs.readFileSync(PATH_TO_CHAIN, 'utf8')
  },
  target : "http://localhost:3000",
  ws: true,
  xfwd: true
};

var server = httpProxy.createProxyServer(options).listen(443);
```

my Meteor app's settings are:
```

ROOT_URL: https://localhost
PORT: 3000
```

**Comment by Tarang** [comment]
Typically you would use the `force-ssl` package to redirect you to port 443. You can't block it entirely since the app proxies SSL requests to port 3000.

An alternative is you could ignore all requests with a source ip that isn't a local one (127.0.0.1)

**Comment by bluefangs** [comment]
Thanks for the quick turnaround @Tarang . How do i do this? "An alternative is you could ignore all requests with a source ip that isn't a local one (127.0.0.1)"
